print(" *** ID card ****")
student_id, firstname, nickname = input("Enter your student_ID firstname nickname : ").split()
print("----------------------------------")
print(f"|{'»-(¯`·.·´¯)->CARD<-(¯`·.·´¯)-«':^32}|")
print(f"|{' ':32}|")
print(f"|{' '+firstname:<16}{student_id+' ':>16}|")
print(f"|{nickname:^32}|")
print(f"|{' ':32}|")
print(f"|{' (-.-)Zzz....':<16}{'(╯︵╰,) ':>15}|")
print("----------------------------------")